# Generated by Django 4.2.4 on 2023-09-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_personalregistrado2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalRegistrado2',
        ),
    ]
